@startuml Classes

interface Named {
    UUID identifier
    String name
}

class Competition {
    Timestamp start
    Timestamp end
    String title
    Map<String, String> Info
}

class Game {
   String title
   Timestamp start
   Timestamp end
   Map<String, String> Info
}

class Player <<Named>> {
    String nickname
    Map<String, String> Info
}

class User {
    UUID userId
}

User --|> Player

interface Team <<Named>>

Team ... Player : "Team Leader"


interface Action {
    Integer scoreDelta
    Team performingTeam
    Player performingPlayer
    String description
    Timestamp startedAt
    Timestamp completedAt
    Map<String, String> info
}

Action ..* Action : Parent
interface Handicap {
    Team recipient
}

interface Penalty 

Penalty --> Player : Recipient
Penalty ..o Handicap : Is part of
Handicap --* Team : Affects
Handicap *-- Game : Occurs during

Competition *-- Game : Occurs during
Action --* Game : Occurs during
Team o--- Game : Participates
Player --* Team : Members

@enduml

@startuml "Football example"

interface Action
interface Penalty
interface Team
interface Game

class FootballGame {
    Team team1
    Team team2
}

FootballGame --|> Game 
FootballGame *-- Goal

class FootballAction {

}

FootballAction --|> Action

class FootballTeam
FootballTeam --|> Team

class FootballPlayer
FootballPlayer --* FootballTeam : belongs to

class FootballPosition {
    String positionName
    Boolean isGoalie
}
FootballPlayer *-- FootballPosition : occupies
FootballPosition *-- FootballAction : starts at
FootballPosition *-- FootballAction : finishes at

class HalfTime as "Half Time"

Goal --|> FootballAction
HalfTime --|> FootballAction
Corner --|> FootballAction
Offside --|> FootballAction
Foul --|> FootballAction
PenaltyKick --|> FootballAction
FreeKick --|> FootballAction
GoalKick --|> FootballAction
PlayerExchange --|> FootballAction

Foul ..> "Yellow Card"
Foul ..> "Red Card"

Foul ..> PenaltyKick : results in
Foul ..> FreeKick : results in
PenaltyKick ..> Goal : results in
FreeKick ..> Goal : results in
"Yellow Card" --|> Penalty
"Red Card" --|> Penalty

class Exclusion <<Handicap>>
"Red Card" --> Exclusion
Exclusion --> FootballTeam : affects
@enduml


@startuml "Volleyball example"

interface Action
interface Penalty
interface Team
interface Game

class VolleyballGame {
    Team team1
    Team team2
}

VolleyballGame --|> Game 
VolleyballGame *-- Point

class VolleyballAction {
}

VolleyballAction --|> Action

class VolleyballTeam
VolleyballTeam --|> Team

class VolleyballPlayer
VolleyballPlayer --|> Player

VolleyballPlayer --* VolleyballTeam : belongs to

class HalfTime as "Half Time"

Point --|> VolleyballAction
HalfTime --|> VolleyballAction
Foul --|> VolleyballAction
Delay --|> VolleyballAction
Serve --|> VolleyballAction
Sideout --|> VolleyballAction

Foul ..> "Yellow Card"
Foul ..> "Red Card"

Penalty --> Player : Recipient

Delay ..> Point : results in
"Yellow Card" --|> Penalty
"Red Card" --|> Penalty

class Exclusion <<Handicap>>
"Red Card" --> Exclusion
Exclusion --> FootballTeam : affects
@enduml

